src/Entity/ExerciseLog.php
<?php

namespace App\Entity;

use App\Repository\ExerciseLogRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExerciseLogRepository::class)]
class ExerciseLog
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $nr_reps = null;


    #[ORM\ManyToOne(inversedBy: 'exerciseLogs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Workout $workout = null;

    #[ORM\ManyToOne(inversedBy: 'exerciseLogs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Exercitii $exercise = null;

    #[ORM\Column(nullable: true)]
    private ?int $duration = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNrReps(): ?int
    {
        return $this->nr_reps;
    }

    public function setNrReps(int $nr_reps): static
    {
        $this->nr_reps = $nr_reps;

        return $this;
    }



    public function getWorkout(): ?Workout
    {
        return $this->workout;
    }

    public function setWorkout(?Workout $workout): static
    {
        $this->workout = $workout;

        return $this;
    }

    public function getExercise(): ?Exercitii
    {
        return $this->exercise;
    }

    public function setExercise(?Exercitii $exercise): static
    {
        $this->exercise = $exercise;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }
}

src/Entity/Exercitii.php
<?php

namespace App\Entity;

use App\Repository\ExercitiiRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ExercitiiRepository::class)]
class Exercitii implements \ArrayAccess
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nume = null;


    #[ORM\ManyToOne(inversedBy: 'exercitiis')]
    private ?Tip $tip_id = null;

    #[ORM\Column(length: 2049, nullable: true)]
    private ?string $link_video = null;

    /**
     * @var Collection<int, ExerciseLog>
     */
    #[ORM\OneToMany(targetEntity: ExerciseLog::class, mappedBy: 'exercise', orphanRemoval: true)]
    private Collection $exerciseLogs;

    public function __construct()
    {
        $this->exerciseLogs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNume(): ?string
    {
        return $this->nume;
    }

    public function setNume(string $nume): static
    {
        $this->nume = $nume;

        return $this;
    }

    public function getLinkVideo(): ?string
    {
        return $this->link_video;
    }

    public function setLinkVideo(string $link_video): static
    {
        $this->link_video = $link_video;

        return $this;
    }

    public function getTipId(): ?Tip
    {
        return $this->tip_id;
    }

    public function setTipId(?Tip $tip_id): static
    {
        $this->tip_id = $tip_id;

        return $this;
    }

    /**
     * @return Collection<int, ExerciseLog>
     */
    public function getExerciseLogs(): Collection
    {
        return $this->exerciseLogs;
    }

    public function addExerciseLog(ExerciseLog $exerciseLog): static
    {
        if (!$this->exerciseLogs->contains($exerciseLog)) {
            $this->exerciseLogs->add($exerciseLog);
            $exerciseLog->setExercise($this);
        }

        return $this;
    }

    public function removeExerciseLog(ExerciseLog $exerciseLog): static
    {
        if ($this->exerciseLogs->removeElement($exerciseLog)) {
            // set the owning side to null (unless already changed)
            if ($exerciseLog->getExercise() === $this) {
                $exerciseLog->setExercise(null);
            }
        }

        return $this;
    }

    public function offsetExists(mixed $offset): bool
    {
        return property_exists($this, $offset);
    }

    public function offsetGet(mixed $offset): mixed
    {
        return $this->$offset;
    }

    public function offsetSet(mixed $offset, mixed $value): void
    {
        $this->$offset = $value;
    }

    public function offsetUnset(mixed $offset): void
    {
        unset($this->$offset);
    }
}

src/Entity/Workout.php
<?php

namespace App\Entity;

use App\Repository\WorkoutRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WorkoutRepository::class)]
class Workout implements \ArrayAccess
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nume = null;

    #[ORM\ManyToOne(inversedBy: 'related_workouts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Tip $tip_id = null;



    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne(inversedBy: 'workouts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    /**
     * @var Collection<int, ExerciseLog>
     */
    #[ORM\OneToMany(targetEntity: ExerciseLog::class, mappedBy: 'workout', orphanRemoval: true)]
    private Collection $exerciseLogs;

    public function __construct()
    {
        $this->exerciseLogs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNume(): ?string
    {
        return $this->nume;
    }

    public function setNume(string $nume): static
    {
        $this->nume = $nume;

        return $this;
    }

    public function getTipId(): ?Tip
    {
        return $this->tip_id;
    }

    public function setTipId(?Tip $tip_id): static
    {
        $this->tip_id = $tip_id;

        return $this;
    }



    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, ExerciseLog>
     */
    public function getExerciseLogs(): Collection
    {
        return $this->exerciseLogs;
    }

    public function addExerciseLog(ExerciseLog $exerciseLog): static
    {
        if (!$this->exerciseLogs->contains($exerciseLog)) {
            $this->exerciseLogs->add($exerciseLog);
            $exerciseLog->setWorkout($this);
        }

        return $this;
    }

    public function removeExerciseLog(ExerciseLog $exerciseLog): static
    {
        if ($this->exerciseLogs->removeElement($exerciseLog)) {
            // set the owning side to null (unless already changed)
            if ($exerciseLog->getWorkout() === $this) {
                $exerciseLog->setWorkout(null);
            }
        }

        return $this;
    }

    public function offsetExists(mixed $offset): bool
    {
        return property_exists($this, $offset);
    }

    public function offsetGet(mixed $offset): mixed
    {
        return $this->$offset;
    }

    public function offsetSet(mixed $offset, mixed $value): void
    {
        $this->$offset = $value;
    }

    public function offsetUnset(mixed $offset): void
    {
        unset($this->$offset);
    }
}

src/Controller/WorkoutController.php
<?php

namespace App\Controller;

use App\Entity\ExerciseLog;
use App\Entity\Workout;
use App\Form\Type\ExerciseUpdateType;
use App\Form\Type\WorkoutType;
use App\Repository\ExerciseLogRepository;
use App\Repository\ExercitiiRepository;
use App\Repository\TipRepository;
use App\Repository\UserRepository;
use App\Repository\WorkoutRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class WorkoutController extends AbstractController
{
    #[Route('/workouts', name: 'workouts_index', methods: ['GET'])]
    public function index(WorkoutRepository $workoutRepository, Request $request, UserRepository $userRepository): Response
    {

        $user = $userRepository->findBy(['userAccount' => $this->getUser()->getId()])[0];
        $search = $request->query->get('search', '');
        if($search != null){ //if we have a filter query for the name field, return the new results
            $workouts = $workoutRepository->findNameBySearchQuery($search);


            return $this->render('workouts/view_workouts.html.twig', [
                'workouts' => $workouts,
                'user' => $user,
            ]);
        }

        $workouts = $workoutRepository->findAll();
        return $this->render('workouts/view_workouts.html.twig', [
            'workouts' => $workouts,
            'user' => $user,
        ]);
    }

    #[Route('/workouts/new', name: 'workouts_new')]
    public function new(Request $request, UserRepository $userRepository, TipRepository $tipRepository,ExercitiiRepository $exercitiiRepository, EntityManagerInterface $entityManager): Response
    {
        $arrayValori = [];
        foreach ($request->getPayload() as $key => $value) {
            $arrayValori[$key] = $value;
        }

        if($arrayValori != [])
        if ($arrayValori['nume'] != null and $arrayValori['user'] != null) { //request validation
            //to create a new workoutf

            $workout = new Workout();
            $workout->setNume($arrayValori['nume']);

            $user = $userRepository->find($arrayValori['user']);
            $workout->setUser($user);

            $date = DateTime::createFromFormat('Y-m-d', $arrayValori['date']);
            $workout->setDate($date);

            $tip = $tipRepository->find(3);

            $workout->setTipId($tip);
            $entityManager->persist($workout);
            $entityManager->flush();


            for($i = 0; $i < count($arrayValori['exercise_id']); $i++) {
                $exerciseLog = new ExerciseLog();

                $exercitiu = $exercitiiRepository->find($arrayValori['exercise_id'][$i]);
                $exerciseLog->setExercise($exercitiu);

                $exerciseLog->setWorkout($workout);
                $exerciseLog->setNrReps($arrayValori['nr_reps'][$i]);


                $exerciseLog->setDuration($arrayValori['duration'][$i]);
                $entityManager->persist($exerciseLog);
                $entityManager->flush();
            }
            return $this->redirectToRoute('workouts_show', ['id' => $workout->getId()], Response::HTTP_SEE_OTHER);
        }
        return $this->render('workouts/new.html.twig', ['exercitiiList' => $exercitiiRepository->findAll(),
            'userList' => $userRepository->findAll(),
            ]);
    }

    #[Route('/workouts/{id}', name: 'workouts_show', methods: ['GET'])]
    public function show(Workout $workout, ExerciseLogRepository $exerciseLogRepository): Response
    {
        $exerciseLogs = $exerciseLogRepository->findAllExerciseLogs($workout->getId());

        return $this->render('workouts/workout.html.twig', [
            'workout' => $workout,
            'exerciseLogs' => $exerciseLogs,
        ]);
    }

    #[Route('/workouts/{id}/edit', name: 'workouts_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ExerciseLogRepository $exerciseLogRepository, Workout $workout, EntityManagerInterface $entityManager, ExercitiiRepository $exercitiiRepository,TipRepository $tipRepository, UserRepository $userRepository): Response
    {


        //process the request if there is one
        $arrayValori = [];
        foreach ($request->getPayload() as $key => $value) {
            $arrayValori[$key] = $value;
        }

        if($arrayValori != []) {

            $logs = $exerciseLogRepository->findAllExerciseLogs($workout->getId());
            //update the workout!
            $workout->setNume($arrayValori['nume']);
            $user = $userRepository->find($arrayValori['user']);
            $workout->setUser($user);
            $entityManager->persist($workout);
            $entityManager->flush();
            if ($arrayValori['nume'] != null and $arrayValori['user'] != null) { //request validation

                if(isset($arrayValori['exercise_id']))
                if (count($logs) > count($arrayValori['exercise_id'])) //if we need to delete the exerciselogs
                {
                    foreach ($logs as $log) {
                        $entityManager->remove($log);
                    }


                    $date = DateTime::createFromFormat('Y-m-d', $arrayValori['date']);
                    $workout->setDate($date);

                    $tip = $tipRepository->find(3);

                    $workout->setTipId($tip);
                    $entityManager->persist($workout);
                    $entityManager->flush();


                    for ($i = 0; $i < count($arrayValori['exercise_id']); $i++) {
                        $exerciseLog = new ExerciseLog();

                        $exercitiu = $exercitiiRepository->find($arrayValori['exercise_id'][$i]);
                        $exerciseLog->setExercise($exercitiu);

                        $exerciseLog->setWorkout($workout);
                        $exerciseLog->setNrReps($arrayValori['nr_reps'][$i]);


                        $exerciseLog->setDuration($arrayValori['duration'][$i]);
                        $entityManager->persist($exerciseLog);
                        $entityManager->flush();
                    }
                    return $this->redirectToRoute('workouts_show', ['id' => $workout->getId()], Response::HTTP_SEE_OTHER);

                } else {
                    $i = 0;
                    for (; $i < count($logs); $i++) {
                        $logs[$i]->setExercise($exercitiiRepository->find($arrayValori['exercise_id'][$i]));
                        $logs[$i]->setNrReps($arrayValori['nr_reps'][$i]);
                        $logs[$i]->setDuration($arrayValori['duration'][$i]);
                        $entityManager->persist($logs[$i]);
                    }

                    for (; $i < count($arrayValori['exercise_id']); $i++) {

                        $exerciseLog = new ExerciseLog();
                        $exerciseLog->setExercise($exercitiiRepository->find($arrayValori['exercise_id'][$i]));
                        $exerciseLog->setWorkout($workout);
                        $exerciseLog->setNrReps($arrayValori['nr_reps'][$i]);
                        $exerciseLog->setDuration($arrayValori['duration'][$i]);
                        $entityManager->persist($exerciseLog);
                    }
                    $entityManager->flush();

                }

            }
            return $this->redirectToRoute('workouts_show', ['id' => $workout->getId()], Response::HTTP_SEE_OTHER);
        }




        $users = $userRepository->findAll();
        $exercises = $exercitiiRepository->findAll();



        return $this->render('workouts/edit_workouts.html.twig', [
            'workout' => $workout,
            'userList'=> $users,
            'exercitiiList' => $exercises,
        ]);
    }

    #[Route('/workouts/{id}', name: 'workouts_delete', methods: ['DELETE'])]
    public function delete(Request $request, Workout $workout, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$workout->getId(), $request->request->get('_token'))) {
            $entityManager->remove($workout);
            $entityManager->flush();
        }

        return $this->redirectToRoute('workouts_index');
    }
}

templates/workouts/edit_workouts.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create New Workout{% endblock %}

{% block body %}
    <div class="container mt-4" data-controller="exercise-form">
        <form method="post" action="{{ path('workouts_edit', {'id': workout.id}) }}" id="workout_form">
            <div class="mb-3">
                <label for="nume" class="form-label">Nume workout:</label>
                <input type="text" id="nume" name="nume" class="form-control" value="{{ workout.nume }}" required>
            </div>

            <div class="mb-3">
                <label for="user" class="form-label">User:</label>
                <select id="user" name="user" class="form-select" required>
                    {% if is_granted('ROLE_ADMIN') %}
                        {% for user in userList %}
                            <option value="{{ user.id }}">{{ user.userAccount.nume }}</option>
                        {% endfor %}

                    {% else %}

                        <option value="{{ app.user.userId.id }}">{{ app.user.nume }}</option>
                    {% endif %}
                </select>
            </div>

            <div class="mb-3">
                <label for="date" class="form-label">Date:</label>
                <input type="date" id="date" name="date" class="form-control" value="{{ workout.date|date('Y-m-d') }}" required>
            </div>
            <div id="exercise_logs" data-exercise-form-target="exerciseLogs">
            {% for log in workout.exerciseLogs  %}

                <div class="exercise-item mb-3 row" data-controller="exercise-form">
                    <hr class="bg-danger border-2 border-top border-danger" />
                    <div id="divExercises" class="col-md-4">
                        <select name="exercise_id[]" class="form-select" required>
                            <option value="{{ log.exercise.id }}">{{ log.exercise.nume }}</option>
                            {% for exercitii in exercitiiList %}
                                <option value="{{ exercitii.id }}">{{ exercitii.nume }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-4">
                        <input type="number" value="{{ log.nrReps }}" name="nr_reps[]" class="form-control" placeholder="Number of Reps" required>
                    </div>
                    <div class="col-md-4">
                        <input type="number" value="{{ log.duration }}" name="duration[]" class="form-control" placeholder="Duration (in seconds)" required>
                    </div>
                </div>

            {% endfor %}
            </div>
            <div class="mb-3" id="locButoane">
                <a href="#" class="btn btn-outline-secondary me-2" data-action="click->exercise-form#addExercise">Add Exercise</a>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>

        <template id="remove-button-exercise-template" data-exercise-form-target="removeButtonExerciseTemplate">
            <a href="#" id="remove-button-exercise" class="btn btn-danger" data-action="click->exercise-form#removeExercise">Remove last exercise</a>
        </template>

        <template id="exercise-template" data-exercise-form-target="exerciseTemplate">
            <div class="exercise-item mb-3 row" data-controller="exercise-form">
                <hr class="bg-danger border-2 border-top border-danger" />
                <div class="col-md-4">
                    <select name="exercise_id[]" class="form-select" required>
                        <option value="">Select Exercise</option>
                        {% for exercitii in exercitiiList %}
                            <option value="{{ exercitii.id }}">{{ exercitii.nume }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-4">
                    <input type="number" name="nr_reps[]" class="form-control" placeholder="Number of Reps" required>
                </div>
                <div class="col-md-4">
                    <input type="number" name="duration[]" class="form-control" placeholder="Duration (in seconds)" required>
                </div>
            </div>
        </template>
    </div>
{% endblock %}

templates/workouts/view_workouts.html.twig
{% extends 'base.html.twig' %}

{% block title %}View Workouts{% endblock %}

{% block body %}

    <div class="container mt-5" data-controller="pagination">
        {% if not is_granted("IS_AUTHENTICATED") %}
            <h1>You must be logged in to view this page.</h1>
            <p><a href="{{ path('app_login') }}" >click here!</a></p>
            {% else %}
        <h1 class="mb-4">Workouts</h1>
        <form method="get" action="{{ path('workouts_index') }}" class="mb-3">
            <div class="input-group">
                <input type="text" name="search" class="form-control" placeholder="Filter by name" value="{{ app.request.query.get('search') }}">
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </form>
        <div class="mb-3">
            <label for="rowsPerPageSelect" class="form-label">Workouts per page:</label>
            <select id="rowsPerPageSelect" class="form-select w-auto" data-pagination-target="perPageSelect" data-action="change->pagination#changeRowsPerPage">
                <option value="5">5</option>
                <option value="10">10</option>
                <option value="30">30</option>
                <option value="50">50</option>
            </select>
        </div>
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Tip</th>
                <th>Date</th>
                <th>User</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody data-pagination-target="tableBody">
            {% for workout in workouts %}
                {% if is_granted('ROLE_ADMIN') %}
                <tr>
                    <td>{{ workout.id }}</td>
                    <td><a href="{{ path('workouts_show', {'id': workout.id}) }}">{{ workout.nume }}</a></td>
                    <td>{{ workout.tipId.nume }}</td>
                    <td>{{ workout.date ? workout.date|date('Y-m-d') : '' }}</td>
                    <td>{{ workout.nume }}</td>
                    <td>
                        <form id="delete-form-{{ workout.id }}" action="{{ path('workouts_delete', {'id': workout.id}) }}" method="post" style="display: inline-block;">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ workout.id) }}">
                            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this workout?')">Delete</button>
                        </form>
                        <a href="{{ path('workouts_edit', {'id': workout.id}) }}" class="btn btn-primary">Edit</a>
                    </td>
                </tr>
                    {% else %}
                        {% if workout.user.id == user.id %}
                            <tr>
                                <td>{{ workout.id }}</td>
                                <td><a href="{{ path('workouts_show', {'id': workout.id}) }}">{{ workout.nume }}</a></td>
                                <td>{{ workout.tipId.nume }}</td>
                                <td>{{ workout.date ? workout.date|date('Y-m-d') : '' }}</td>
                                <td>{{ workout.nume }}</td>
                                <td>
                                    <form id="delete-form-{{ workout.id }}" action="{{ path('workouts_delete', {'id': workout.id}) }}" method="post" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ workout.id) }}">
                                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this workout?')">Delete</button>
                                    </form>
                                    <a href="{{ path('workouts_edit', {'id': workout.id}) }}" class="btn btn-primary">Edit</a>
                                </td>
                            </tr>
                            {% endif %}
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        <nav>
            <ul class="pagination justify-content-center" data-pagination-target="pagination"></ul>
        </nav>

        {% if is_granted("IS_AUTHENTICATED") %}
        <a href="{{ path('workouts_new') }}" class="btn btn-success">New Workout</a>
        {% endif %}

        {% endif %}
    </div>
{% endblock %}

templates/workouts/workout.html.twig
{% extends 'base.html.twig' %}

{% block title %}Workout Details{% endblock %}


{% block body %}

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header text-center bg-dark text-white">
                        <h2>Workout Details</h2>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title text-center">{{ workout.nume }}</h4>
                        <p class="card-text text-center"><strong>Tip:</strong> {{ workout.tipId.nume }}</p>
                        <p class="card-text text-center"><strong>Date:</strong>                     {% if  workout.date is not null %}
                                {{  workout.date|date('Y-m-d') }}

                            {% endif %}</p>
                        <p class="card-text text-center"><strong>User:</strong> {{ workout.user.userAccount.nume }}</p>

                        {% for exerciseLog in exerciseLogs %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="flush-heading{{ exerciseLog.id }}">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{ exerciseLog.id }}" aria-expanded="false" aria-controls="flush-collapseOne">
                                        <input class="form-check-input"  disabled="true" type="checkbox" value="" id="check{{exerciseLog.exercise.id}}{{ exerciseLog.duration }}">&emsp;{{ exerciseLog.exercise.nume}}
                                    </button>
                                </h2>
                                <div id="flush-collapse{{ exerciseLog.id }}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{ exerciseLog.id }}" data-bs-parent="#accordionFlushExample">
                                    <div class="accordion-body" data-controller="timer">
                                        Number of reps: {{ exerciseLog.nrReps }}</br>
                                        Duration: {{ exerciseLog.duration }} seconds</br>
                                        Video Instructions:<br>
                                        <div class="embed-responsive embed-responsive-16by9">
                                            <iframe class="embed-responsive-item" src="{{ exerciseLog.exercise.linkVideo }}" allowfullscreen></iframe>
                                        </div>
                                        <button class="btn btn-primary mt-3" data-action="click->timer#startTimer" data-exercise_id="{{ exerciseLog.exercise.id }}" data-duration="{{ exerciseLog.duration }}" data-name="{{ exerciseLog.exercise.nume }}">Start Timer</button>
                                        <audio id="success-sound" src="{{ asset('sound/times_up.wav') }}"></audio>
                                    </div>
                                </div>


                            </div>
                        {% endfor %}

                        </div>
                    </div>
                </div>
                <div class="text-center mt-4">
                    <a href="{{ path('workouts_index') }}" class="btn btn-primary">Back to Workouts</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}